name: Build PC ESP EXE
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        sudo apt-get update && sudo apt-get install -y g++-mingw-w64-x86-64
        x86_64-w64-mingw32-g++ -o ff_esp.exe pc_esp/main.cpp -lgdi32 -luser32 -static -O2 -std=c++17 -w
    - uses: actions/upload-artifact@v4
      with:
        name: ff-esp-exe
        path: ff_esp.exe
